SEARCHING, FILTERING AND SORTING

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7])


Cercare l'indice di un certo elemento: WHERE

Viene chiamato con np.where() dove inseriamo l'array e cosa vogliamo cercare al suo interno.
Ci ritorno l'indice il cui elemento corrisponde a quello che abbiamo cercato.

In [3]:
arrIndici = np.where(arr == 4)
print(arrIndici)

(array([3]),)


In [4]:
#questo ci ritorna gli indici di tutti gli elementi pari
arrIndici = np.where(arr %2 == 0)
print(arrIndici)

(array([1, 3, 5]),)


SORT

In [5]:
arr = np.array([3,1,5,7,4,2,6])
print(np.sort(arr))  #ritorna una copia ordinata dell'array senza modificare l'originale. 
#Funziona anche con le stringhe e ci ritorna sempre un array ordinato.

[1 2 3 4 5 6 7]


In [10]:
#Array multidimensionali
arr2D = np.array([[3,1,5],
                  [7,4,2],
                  [6,8,9]])
print(np.sort(arr2D)) #ordina ogni riga

[[1 3 5]
 [2 4 7]
 [6 8 9]]


FILTRARE: ESEMPIO STATICO, DINAMICO E SCORCIATOIA

In [ ]:
arr = np.array([1,2,3,4])
#ESEMPIO STATICO: numeri dispari
filtro = [True, False, True, False]

arrayFiltrato = arr[filtro] #prende solo i valori che sono True
print(arrayFiltrato) 

[1 3]


In [ ]:
#ESEMPIO DINAMICO: numeri pari
arr = np.array([1,2,3,4])
filtro = []
for numero in arr:
    if numero %2 == 0:
        filtro.append(True) #come con le liste
    else:
        filtro.append(False)

arrayFiltrato = arr[filtro] #prende solo i valori che sono True
print(arrayFiltrato) 

[2 4]


In [15]:
#SCORCIATOIA: numeri pari
arr = np.array([1,2,3,4])
filtro = arr%2 == 0
arrayFiltrato = arr[filtro] #prende solo i valori che sono True
print(arrayFiltrato) 

[2 4]
