RANDOM: GENERARE UN ARRAY RANDOM CON RANDINT E RAND, CHOICE PER ESTRARRE UN VALORE E GENERARE ARRAY
        DISTRIBUZIONE DATI CON PROBABILITA', SHUFFLE E PERMATUTION

In [13]:
import numpy as np
from numpy import random, array, size

In [6]:
#RANDINT
numero = random.randint(100) #numero casuale tra 0 e 100
print(numero)

31


In [9]:
#ARRAY RANDOM CON RANDINT
arr = random.randint(100, size=(15)) #array monodimensionale di 15 numeri casuali tra 0 e 100
print(arr)

arr2 = random.randint(100, size=(2, 10)) #array bidimensionale di 10 numeri casuali tra 0 e 100
print(arr2)

[35  2 76 14  9 14 22 37 75 60 28 88 85 91 47]
[[56 15 12  8 57 51 45 29 48 74]
 [ 0 18 39 82  6 96  0 47 52  7]]


In [11]:
#ARRAY RANDOM CON RAND
arr = random.rand(5) #array monodimensionale di 5 numeri casuali tra 0 e 1
print(arr)

#a differenza di randint, con rand non serve specificare il limite massimo perchè è sempre 1

arr2 = random.rand(5, 2) #array bidimensionale di 5 righe e 2 colonne
print(arr2)

[0.30026467 0.12718729 0.32019847 0.52319089 0.58451662]
[[0.53223345 0.57569605]
 [0.02522541 0.73162547]
 [0.43056891 0.76438762]
 [0.22130373 0.84214707]
 [0.12475409 0.89135054]]


CHOICE

In [14]:
arr = np.arange(1, 10)
print(random.choice(arr)) #estrae un numero casuale dall'array

6


In [15]:
#Con choice possiamo creare un array composto da numeri estratti casualmente da un altro array
arrChoice = random.choice(arr, size=5) #array monodimensionale con 5 numeri estratti casualmente da arr
print(arrChoice)

[6 2 4 9 1]


PROBABILITA'

In [18]:
arr = np.arange(1, 10)
prob = np.array([0.1, 0.2, 0.2, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05]) #probabilità associate a ciascun numero
arrChoice = random.choice(arr, p=prob, size=5)
print(arrChoice)
#quindi usando delle probabilità possiamo influenzare l'estrazione dei numeri casuali

[1 8 3 3 2]


SHUFFLE E PERMUTATION

In [19]:
arr = np.arange(1, 10)

In [ ]:
#SHUFFLE
random.shuffle(arr) #modifica l'array originale mescolandolo, quindi agisce sull'array originale
print(arr)

[8 2 6 9 1 5 4 3 7]


In [ ]:
#PERMUTATION
arrPermut = random.permutation(arr) #dobbiamo assegnare il risultato a una nuova variabile
print(arrPermut) #crea una copia dell'array originale mescolata, quindi l'array originale non viene modificato

[2 4 9 1 7 3 6 5 8]
