FUNZIONI UNIVERSALI (UFUNC) E COME CREARLE 
+ 
ESEMPI DI UFUNC(ADD, SUBTRACT, DIVIDE, POWER, REMAINDER, TRUC, CEIL, FLOOR, SUM, DOT)

In [1]:
import numpy as np

In [3]:
#Come vedere il tipo di una funzione
print(type(np.add))

<class 'numpy.ufunc'>


CREARE LA UFUNC

In [ ]:
def add5(x):
    return x + 5

add5 = np.frompyfunc(add5, 1, 1)
#questa operazione trasforma la funzione in una ufunc, quindi è importante per registrarla
#per farlo uso np.frompyfunc(nome_funzione, numero di input, numero di output)
#questo serve per far si che la funzione possa essere applicata a array numpy
#e non solo a singoli valori
#Se avessimo ua lista come input e non usassimo frompyfunc, otterremmo un errore perchè la funzione non è in grado di gestire liste
#con frompyfunc invece la funzione viene trasformata in una ufunc e può essere applicata a array numpy

arr =np.arange(1,6)
print(add5(arr))

[6 7 8 9 10]


ADD FUNCTION

In [7]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([5,10,15,20,25])


In [ ]:
print(np.add(arr1, arr2)) #funziona anche con liste

[15 30 45 60 75]


SUBTRACT FUNCTION

In [9]:
print(np.subtract(arr1, arr2))

[ 5 10 15 20 25]


MULTIPLY FUNCTION

In [10]:
print(np.multiply(arr1, arr2))

[  50  200  450  800 1250]


DIVIDE FUNCTION

In [11]:
print(np.divide(arr1, arr2))

[2. 2. 2. 2. 2.]


POWER FUNCTION

In [12]:
print(np.power(arr1, arr2))

[              100000       10240000000000 -2659889346031157248
  1152921504606846976   187601812243611648]


MOD/REMAINDER FUNCTION (resto della divisione)

In [14]:
print(np.remainder(arr1, arr2))

[0 0 0 0 0]


TRUNC: per arrotondare al primo intero (uguale a .fix(), around())

CEIL: arrotondare per eccesso

FLOOR: arrotondare per difetto

In [ ]:
arr = np.trunc([1.5, 2.765, 3.432, 4.123, 5.567]) #per arrotondare al primo intero (uguale a .fix(), around())
print(arr)
arr = np.ceil([1.5, 2.765, 3.432, 4.123, 5.567]) #arrotondare per eccesso
print(arr)
arr = np.floor([1.5, 2.765, 3.432, 4.123, 5.567]) #arrotondare per difetto
print(arr)

[1. 2. 3. 4. 5.]
[2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5.]


FUNZIONE SUM: ci permette di sommare tutti gli elementi di un array

In [ ]:
a = np.array([1, 2, 3, 4]) #una dimensione
print(a.sum())

10


In [8]:
b = np.array([[1, 2, 3], 
              [4, 5, 6]]) #due dimensioni
print(b.sum()) #somma tutti gli elementi
print(b.sum(axis=0)) #somma le colonne
print(b.sum(axis=1)) #somma le righe

21
[5 7 9]
[ 6 15]


In [10]:
c = np.random.rand(2, 3, 4) #tre dimensioni
print(c.sum(axis=(0, 1))) #somma per riga e colonna

[3.17883684 1.77454007 1.92520427 2.26326142]


FUNZIONE DOT:  ci permette di effettuare l'operazione di moltiplicazione matriciale riga per colonna, 
                quindi il prodotto matriciale. Una matrice ha 2x1 e l'altra 1x2 otteniamo una matrice 2x2.

In [ ]:
a = np.array([[1, 2]])
b = np.array([[3], 
              [4]])
print(a.dot(b)) #la matrice di sinistra richiama dot e come argomento ha la matrice di destra

[[11]]


In [ ]:
print(b.dot(a)) #matrici invertite(occhio alla regola delle dimensioni)

[[3 6]
 [4 8]]
