1. Esercizio

Scrivere una funzione che restituisca il prodotto riga per colonna di due vettori v1 e v2. Utilizzare in primis una list comprehension, verificando anche che la lunghezza dei due vettori sia coerente. Valutare inoltre il tempo necessario all'esecuzione utilizzando la libreria time.

Effettuare la stessa operazione in NumPy, valutando contestualmente il tempo necessario in entrambi i casi.

In [ ]:
import numpy as np

In [16]:
v1 = np.array([[1, 2, 3]])
v2 = np.array([[4],
               [5],
               [6]])

In [17]:
def riga_per_colonna(v1, v2):
    if v1.shape[0] == 1:
        if v2.shape[1] == 1 and v1.shape[1] == v2.shape[0]:
            prod = sum([v1[0][i] * v2[i] for i in range(v2.shape[0])])
    elif v2.shape[0] == 1:
        if v1.shape[1] == 1 and v2.shape[1] == v1.shape[0]:
            prod = sum([v1[i] * v2[0][i] for i in range(v1.shape[0])])
    else:
        return ("Le dimensioni non sono coerenti!")
    return prod

print(riga_per_colonna(v1, v2))

[32]


In [13]:
#con numpy
res = np.dot(v1, v2)
print(res)

[[32]]


2. Esercizi

Scrivere la funzione crea_array(dim_1, dim_2, val_min, val_max) che crea array di dimensione arbitraria dim_1xdim_2 composti da numeri interi casuali compresi tra val_min e val_max. Di default, la funzione dovrà creare dei vettori riga. Utilizzare il package random.
Provare ad effettuare la stessa operazione in NumPy.

In [18]:
import numpy as np
from numpy import random

In [37]:
def crea_array(dim_1, dim_2=1, val_min=0, val_max=100):
    rows = [[random.randint(val_min, val_max) for i in range(dim_2)] for j in range(dim_1)]
    return np.array(rows)

print(crea_array(3))

[[78]
 [68]
 [69]]


In [ ]:
arr = random.randint(min, max, size=(1, 3))
print(arr)

[[58 65]]


3. Esercizio

Scrivere la funzione rettifica(array) che restituisce un array analogo a quello in ingresso, ma con tutti i valori negativi "rettificati" a 0.

In [41]:
import numpy as np

def rettifica(arr):
    arr[arr < 0] = 0 #tutti gli elementi di arr che sono <0 vengono messi a 0
    return arr

arr =np.array([[1, -2, 3], 
               [-4, 5, -6]])
new_arr = rettifica(arr)
print(new_arr)



[[1 0 3]
 [0 5 0]]


Esercizio 2.1.4

Verificare che il prodotto tra una matrice invertibile e la sua inversa sia la matrice identità.

In [3]:
import numpy as np
from numpy import linalg 

mat = np.array([[2,1,3],
               [0,-1,-4],
               [1,2,1]])

mat_Inv = linalg.inv(mat)

np.matmul(mat, mat_Inv)

array([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17, -5.55111512e-17,  1.00000000e+00]])

Esercizio 2.1.5

Scrivere la funzione calcola_determinante() che accetta come parametro in ingresso una matrice 2x2 e ne calcola il determinante. Gestire opportunamente il caso in cui la matrice in ingresso sia difforme dalle indicazioni fornite in precedenza, o che non la matrice non sia invertibile.

In [6]:
import numpy as np
from numpy import linalg

a = np.array([[4, 3],
              [6, 3]])

def calcola_determinante(mat):
    if len(mat.shape) == 2:
        if mat.shape[0] != mat.shape[1]:
            return "La matrice non è quadrata!"
        det = linalg.det(mat)
        if det == 0:
            return "La matrice non è invertibile!"
        return det
    else:
        raise ValueError('La matrice non ha le dimensioni attese.')

print(calcola_determinante(a))

-6.0


Esercizio 2.1.6

Scrivere la funzione inverti_se_invertibile(mat) che, data una matrice bidimensionale, restituisca l'inversa soltanto se mat è bidimensionale, quadrata, e il determinante è diverso da zero. Utilizzare un'unica istruzione condizionale.

In [8]:
import numpy as np
from numpy import linalg

a = np.array([[4, 3],
              [6, 3]])

def inverti_se_invertibile(mat):
    if len(mat.shape) == 2 and mat.shape[0] == mat.shape[1] and linalg.det(mat) != 0:
        return linalg.inv(mat)
    else:
        raise ValueError('La matrice non è invertibile.')

print(inverti_se_invertibile(a))
    


[[-0.5         0.5       ]
 [ 1.         -0.66666667]]
