INDICIZZAZIONE ARRAY +  INDICIZZAZIONE NEGATIVA + DELETE + INSERT

In [2]:
import numpy as np

In [ ]:
arr1D = np.array([1, 2, 3, 4, 5])
print(arr1D[0])  # Output: 1
#come per le liste, l'indicizzazione inizia da 0

1


In [9]:
#voglio prendere il numero 3
arr2D = np.array([[1, 2, 3], 
                  [4, 5, 6]])
print(arr2D[0,2])  # Output: 3
#Il primo indice seleziona il primo array (riga), 
#il secondo indice seleziona l'elemento all'interno di quell'array

3


In [14]:
#voglio prendere il numero 7
arr3D = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
print(arr3D[1,1,0])  # Output: 7

print(arr3D[0][0][0], arr3D[0][0][1])  # Output: 1 2

7
1 2


INDICIZZAZIONE NEGATIVA

In [ ]:
print(arr3D[1,1,-1]) # Output: 8
#L'indicizzazione negativa inizia dalla fine dell'array, come con le liste
#L'ultimo elemento ha indice -1, il penultimo -2, e così via

8


DELETE: ci permette di rimuovere uno o più elementi di un array specificandone gli indici.
La funzione accetta i seguenti parametri:
-arr: l'array sul quale vogliamo effettuare l'operazione di rimozione;
-obj: gli indici degli elementi da rimuovere;
-axis: l'asse su cui vogliamo operare.

In [3]:
arr = np.array([1, 2, 3, 4]) #una dimensione
print(np.delete(arr, 0)) #eliminiamo elemento in posizione 0. Questo non modifica l'array originale

[2 3 4]


In [5]:
#Usiamo axis
mat = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]]) #più dimensioni
print(np.delete(mat, 0, axis = 0)) #questo elimina la prima riga

[[4 5 6]
 [7 8 9]]


In [6]:
mat = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
np.delete(mat, 0, axis = 1) #questo elimina la prima colonna

array([[2, 3],
       [5, 6],
       [8, 9]])

In [7]:
#Se non specifichiamo axis, l'array viene appiattito in un array 1D prima di rimuovere gli elementi
mat = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
np.delete(mat, 0)

array([2, 3, 4, 5, 6, 7, 8, 9])

INSERT: permette di inserire un elemento all'interno di un array nel punto che vogliamo noi.
I parametri accettati dalla funzione sono:
-arr: l'array sul quale vogliamo effettuare l'operazione di inserzione;
-obj: gli indici su cui inserire i nuovi valori;
-values: i valori da inserire agli indici specificati da obj;
-axis: l'asse su cui vogliamo operare.

APPEND funziona in modo similare, solo che inserisce solo alla fine dell'array.

In [8]:
mat = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
np.insert(mat, 3, [10, 11, 12], axis = 0) #inseriamo una nuova riga in posizione 3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
np.insert(mat, 3, [10, 11, 12], axis = 1) #inseriamo una nuova colonna in posizione 3

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [10]:
#senza axis
np.insert(mat, 9, 10) #inseriamo il valore 10 in posizione 9 dell'array appiattito

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])