SLICING ARRAY + SLICING NEGATIVO

In [2]:
import numpy as np

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
#E se volessi prendere solo qualche elemento dell'array? Tipo da x a y?
print(arr[0:2])  # Output: [1, 2]
# In questo caso, prendo gli elementi dall'indice 0 all'indice 2 (escluso l'indice 2)

print(arr[1:3]) # Output: [2, 3]
# In questo caso, prendo gli elementi dall'indice 1 all'indice 3 (escluso l'indice 3)

[1 2]
[2 3]


In [6]:
print(arr[2:]) # Output: [3, 4, 5]
# In questo caso, prendo gli elementi dall'indice 2 fino alla fine dell'array

[3 4 5]


In [7]:
print(arr[:3]) # Output: [1, 2, 3]
# In questo caso, prendo gli elementi dall'inizio dell'array fino all'indice 3 (escluso l'indice 3)

[1 2 3]


SLICE NEGATIVO

In [8]:
print(arr[2:-1]) # Output: [3, 4]
# In questo caso, prendo gli elementi dall'indice 2 fino all'indice -1 (escluso l'indice -1)

[3 4]


In [9]:
print(arr[-3:-1]) # Output: [3, 4]
# In questo caso, prendo gli elementi dall'indice -3 all'indice -1 (escluso l'indice -1)

[3 4]


STEP = PRENDERE DEGLI ELEMENTI IN UN RANGE MA SALTANDO

In [ ]:
# oppure arr = np.arange(11)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
print(arr[0:8:2]) # Output: [1, 3, 5, 7]
# In questo caso, prendo gli elementi dall'indice 0 all'indice 8 (escluso l'indice 8) saltando di 2 in 2

[1 3 5 7]


In [ ]:
print(arr[::2]) # Output: [1, 3, 5, 7, 9]
# In questo caso, prendo tutti gli elementi dell'array saltando di 2 in 2

[1 3 5 7 9]


ARRAY DI PIU' DIMENSIONI

In [ ]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
print(arr2D[1,1:]) # Output: [5, 6]
# In questo caso, prendo gli elementi della seconda riga (indice 1) dall'indice 1 fino alla fine

[5 6]


In [18]:
arr3D = np.array([
                  [[1, 2], [3, 4]], 
                  [[5, 6], [7, 8]]
                  ])
print(arr3D[1,0,:]) # Output: [5, 6]
# In questo caso, prendo gli elementi del secondo "blocco" (indice 1), prima riga (indice 0), 
# dall'indice 0 fino alla fine

[5 6]
