VIEW E COPY

In [1]:
import numpy as np

View e copy a livello teorico servono entrambi per copiare il contenuto di un array in ul altro array.
La differenza è:
- copy fa una copia effettiva dell'array e modificando l'array copiato non si va a modificare quello originale.     Quindi siamo proprietari dell'array modificato
- view ci permette solo di vedere l'originale, senza esserne proprietari


In [ ]:
# Come creare una COPIA
arr = np.array([1,2,3])
arrCopy = arr.copy()  # copia effettiva

#Quindi con .copy() siamo proprietari dell'array copiato e possiamo modificarlo senza modificare l'originale

[1 2 3]
[1 2 3]


In [ ]:
#Andiamo a modificare l'originale? l'array copiato non cambia
arr[0] = 10

In [8]:
print(arr)
print(arrCopy)


[10  2  3]
[1 2 3]


In [ ]:
#come creare una VIEW
arr = np.array([1,2,3])
arrView = arr.view()

#Con .view() non siamo proprietari dell'array e quindi se modifichiamo l'originale, anche la view cambia

In [ ]:
arr[0] = 10
#Andiamo a modificare l'originale? La View cambia

In [11]:
print(arr)
print(arrView)

[10  2  3]
[10  2  3]


In [12]:
#Per capire se siamo proprietari di un array, possiamo usare l'attributo base, 
# che restituisce None se l'array è proprietario. Se non è proprietario, restituisce l'array originale.
print(arr.base)      # None, perchè è proprietario
print(arrView.base)  # restituisce arr, perchè non è proprietario

None
[10  2  3]
