SHAPE E RESHAPE

- Shape ci permette di vedere la forma di un array
- Reshape ci permette di cambiare la forma del nostro array. Può essere fatto solamente quando la combinazione delle 
dimensioni che vogliamo ottenere ci dia come risultato il numero di elementi (o lunghezza) che abbiamo nell'array.

Esempio: se abbiamo 12 elementi possiamo fare tipo 4*3 oppure 2*3*2 ma non 3*3

In [2]:
import numpy as np

In [ ]:
arr = np.array([1,2,3])
print(arr.shape) #il comando è .shape
#ci restitiuisce una tupla con il numero di elementi per ogni dimensione
#in questo caso (3,) perchè è un array monodimensionale con 3 elementi

(3,)


In [ ]:
arr = np.array([[1,2,3], [3,4,5]])
print(arr.shape)
#in questo caso (2,3) perchè è un array bidimensionale con 2 dimensioni e 3 elementi per ogni dimensione
#quindi due righe e tre colonne

(2, 3)


In [ ]:
#RESHAPE
print(arr.reshape(-1)) #il comando è .reshape
#in questo caso (-1) ci restituisce un array monodimensionale con tutti gli elementi

print(arr.reshape(-1).base)
#come possiamo vedere, sarebbe una View dell'array originale

[1 2 3 3 4 5]
[[1 2 3]
 [3 4 5]]


In [13]:
#possiamo anche aumentare le dimensioni
arr =np.arange(1,13)
print(arr.reshape(4,3)) #4 righe e 3 colonne
#in questo caso (4,3) perchè è un array bidimensionale con 4 dimensioni e 3 elementi per ogni dimensione

print(arr.reshape(2,2,3)) #2 matrici di 2 righe e 3 colonne
#in questo caso (2,2,3) perchè è un array tridimensionale con 2 matrici, 2 righe e 3 colonne

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#nel caso non sapessimo quante righe o colonne vogliamo per una dimensione, possiamo usare -1
#in questo caso numpy calcolerà automaticamente il numero di righe o colonne che ci servono
print(arr.reshape(2,-1,3)) #2 matrici di 2 righe e 3 colonne

#Questo funziona solo quando usiamo un solo -1!

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
#Flattening : passare da un array multidimensionale a uno monodimensionale
arr3D = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
#le possibilità sono due: usare reshape(-1) oppure usare il comando flatten()
print(arr3D.reshape(-1))
print(arr3D.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
