ITERARE UN ARRAY CON:
- PIU' DIMENSIONI; 
- NDITER; 
- CAMBIARE TIPO DI DATO; 
- ITERARE A STEP;
- PRENDERE INDICE DELL'ITERAZIONE

In [3]:
import numpy as np
#UNA DIMENZIONE
arr = np.arange(1,7)
for x in arr:
    print(x)

1
2
3
4
5
6


In [ ]:
#DUE DIMENSIONI
arr2D = np.array([[1,2,3], 
                  [4,5,6]])
for x in arr2D:
    print(x) #ci stampa ogni riga o dimensione che sono due

[1 2 3]
[4 5 6]


In [5]:
#Per accedere a ogni elemento dobbiamo fare un altro ciclo
for x in arr2D:
    for y in x:
        print(y) #ci stampa ogni elemento

1
2
3
4
5
6


In [6]:
#TRE DIMENSIONI
arr3D = np.array([[[1,2,3], [4,5,6]], 
                  [[7,8,9], [10,11,12]]])

for x in arr3D:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [7]:
#per accedere a ogni elemento dobbiamo fare un altro ciclo
for x in arr3D:
    for y in x:
        for z in y:
            print(z) #ci stampa ogni elemento

1
2
3
4
5
6
7
8
9
10
11
12


In [8]:
#Più velocemente si può usare il medoto nditer() dove:
#- n vuol dire fare una cosa n volte
#- d sta per dimensione
#- iter sta per iterare
#Quindi iterare per il numero di dimensioni
#Per usarlo dobbiamo richiamare nditer() da numpy e passargli l'array
for x in np.nditer(arr3D):
    print(x) #ci stampa ogni elemento

1
2
3
4
5
6
7
8
9
10
11
12


In [9]:
#NDITER ci permette anche di cambiare il tipo di dato
for x in np.nditer(arr3D, flags=['buffered'], op_dtypes=['S']):
    print(x) #ci stampa ogni elemento come stringa

#Dobbiamo richiamar il buffered perchè altrimenti non funziona
#op_dtypes specifica il tipo di dato che vogliamo ottenere come output(op) è una stringa

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')
np.bytes_(b'10')
np.bytes_(b'11')
np.bytes_(b'12')


In [ ]:
#Iterare a step
arr2D = np.array([[1,2,3], 
                  [4,5,6]])
for x in np.nditer(arr2D[:,::2]): #prende ogni due elementi
    print(x)

#i primi : servono per prendere tutte le righe
#il secondo : serve per prendere tutte le colonne
#il :2 serve per prendere ogni due elementi

1
3
4
6


In [ ]:
#PRENDERE L'INDICE DELL'ITERAZIONE
#Usiamo il metodo ndenumerate() che ci restituisce sia l'indice che il valore  
for idx, x in np.ndenumerate(arr2D):
    print(idx, x) #ci stampa l'indice relativo ad ogni dimensione e il valore

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
