UNIRE ARRAY
- concatenate
- stack

In [ ]:
import numpy as np
#UNA DIMENSIONE
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

CONCATENATE

Il metodo è np.concatenate() che richiede come argomento gli array che vogliamo concatenare. Gli array vanno passati come se fossero una dimensione

In [ ]:
arr = np.concatenate((arr1, arr2))
print(arr) #l'array ha una dimensione

[1 2 3 4 5 6]


In [ ]:
#DUE DIMENSIONi
arr1 = np.array([[1,2], 
                 [3,4]])
arr2 = np.array([[5,6], 
                 [7,8]])
arr = np.concatenate((arr1, arr2))
print(arr) #l'array ha due dimensioni

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr1 = np.array([[1,2], 
                 [3,4]])
arr2 = np.array([[5,6], 
                 [7,8]])
arr = np.concatenate((arr1, arr2), axis = 1)
print(arr)
#così facendo concatena [1,2] con [5,6] e così via

[[1 2 5 6]
 [3 4 7 8]]


STACK, HSTACK, VSTACK E DSTACK

Il metodo è np.stack() e come con concatenare ci vuole la doppia ().
Stack funziona diversamente da concatenate. 
Con concatenate, quando uniamo due array di una dimensione, otteniamo un array unico con una dimensione.
Mentre con stack otteniamo un array di due dimensioni che corrispondono ai due array monodimensionali che abbiamo unito

- Hstack viene chiamato con np.hstack() e unisce orizzontalmente. E' l'equivalente di un concatenate con axis = 0
- Vstack viene chiamato con np.vstack() e unisce verticalmente. E' l'equivalente di un stack con axis = 0
- Dstack viene chiamato con np.dstack(). E' l'equivalente di un stack con axis = 1 e aggiunge una dimensione
- Stack ci permette di unire con più in libertà e aggiunge una dimensione

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arrConc = np.concatenate((arr1, arr2))
arrStack = np.stack((arr1, arr2))

print(arrConc)
print(arrStack)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [11]:
# arrConc = np.concatenate((arr1, arr2), axis = 1) questo non funziona
arrStack = np.stack((arr1, arr2), axis = 1) #con stack funziona
print(arrStack)

[[1 4]
 [2 5]
 [3 6]]


In [12]:
#Hstack
arrStack = np.hstack((arr1, arr2))
print(arrStack)

[1 2 3 4 5 6]


In [13]:
#Vstack
arrStack = np.vstack((arr1, arr2))
print(arrStack)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Dstack
arrStack = np.dstack((arr1, arr2))
print(arrStack) #ha aggiunto una dimensione

[[[1 4]
  [2 5]
  [3 6]]]
